
source 'http://rubygems.org'
ruby '2.2.0'

gem 'rails', '4.2.1'
gem 'sass-rails', '>= 3.2'
gem 'compass-rails', '~> 2.0.alpha.0'
gem 'uglifier', '2.5.1'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.1.1'
gem 'jquery-ui-rails'
gem 'jbuilder'
gem 'kaminari'
gem 'responders'
gem 'bcrypt'
gem 'devise'
gem 'pg'
gem 'comfortable_mexican_sofa', '1.12.7'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'paperclip'
gem 'aws-sdk'
gem 'mail_form'
gem 'simple_form'
gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'rails-4-2'
gem 'skrollr-rails'
gem 'rails_admin'
gem 'picturefill'
gem 'autoprefixer-rails'
gem 'chronic'
gem 'acts_as_xlsx'
gem 'axlsx'
gem 'axlsx_rails'
gem 'rubyzip'
gem 'writeexcel', '1.0.5'
gem 'figaro'
gem 'meta-tags'
gem 'metamagic'
gem 'safe_yaml', '1.0.4'
gem 'sitemap_generator'
gem 'dynamic_sitemaps'
gem 'fullcalendar-rails'
gem 'momentjs-rails'
gem 'jquery-datetimepicker-rails'
gem 'cocoon'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'masonry-rails'
gem 'omniauth', '~> 1.2.2'
gem 'omniauth-google-oauth2'
gem 'json'
gem 'instagramjs-rails'
gem 'will_paginate', '~> 3.0.6'
gem 'dalli'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'jquery-slick-rails'
gem 'koala', '~> 2.2'
gem 'jquery-scrollto-rails'

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
  gem 'foreman'
  gem 'pry-rails'
  gem 'unicorn'
  gem 'rails-dev-tweaks', '~> 1.1'
end

group :production do
  gem 'rails_12factor'
  gem 'unicorn-rails'
end
