source 'http://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0'
gem 'compass-rails', '~> 2.0.alpha.0'
gem 'uglifier', '2.5.1'
gem 'coffee-rails', '4.1.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 2.0'
gem 'kaminari'
gem 'responders'
gem 'bcrypt'
gem 'dotenv-rails', :groups => [:development, :test], :require => 'dotenv/rails-now'
gem 'devise'
gem 'pg'
gem 'comfortable_mexican_sofa', '1.12.7'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'paperclip', :git => 'https://github.com/thoughtbot/paperclip', :ref => '523bd46c768226893f23889079a7aa9c73b57d68'
gem 'aws-sdk'
gem 'mail_form'
gem 'simple_form'
gem 'rails_admin'
gem 'picturefill'
gem 'autoprefixer-rails'
gem 'chronic'
gem 'acts_as_xlsx'
gem 'axlsx'
gem 'axlsx_rails'
gem 'rubyzip'
gem 'writeexcel', '1.0.5'
gem 'figaro'
gem 'meta-tags'
gem 'metamagic'
gem 'sitemap_generator'
gem 'dynamic_sitemaps'
gem 'fullcalendar-rails'
gem 'momentjs-rails'
gem 'jquery-datetimepicker-rails'
gem 'cocoon'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'masonry-rails'

gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-linkedin'
gem 'omniauth-google-oauth2'

gem 'json'
gem 'instagramjs-rails'
gem 'dalli'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'jquery-slick-rails'
gem 'koala', '~> 2.2'
gem 'jquery-scrollto-rails'
gem 'font_assets'
gem 'font-awesome-rails'
gem 'cancancan', '~> 1.10'

gem 'jscrollpane-rails'
gem 'spring',        group: :development
gem 'rack-cors', :require => 'rack/cors'

group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
  gem 'foreman'
  gem 'pry-rails'
  gem 'unicorn-rails'
  gem 'rails-dev-tweaks', '~> 1.1'
  gem 'rspec-rails', '~> 3.5'
end

group :production do
  gem 'rails_12factor'
  gem 'unicorn-rails'
end
